/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VentanasAdmin;

import ModeloUML.*;
import g2vjovi.*;
import java.util.ArrayList;

/**
 *
 * @author 1gbd02
 */
public class BuscarTrabajador extends javax.swing.JDialog {
    /**
     * Creates new form BuscarTrabajador
     */
    private G2vJovi main = new G2vJovi();
    public BuscarTrabajador(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        bBuscar = new javax.swing.JButton();
        bSalir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfNombreCentro = new javax.swing.JTextField();
        tfIdCentro = new javax.swing.JTextField();
        rbCentroId = new javax.swing.JRadioButton();
        rbCentroNombre = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbTrabajador = new javax.swing.JCheckBox();
        cbCentro = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        tfNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfDni = new javax.swing.JTextField();
        rbTrabajadorDni = new javax.swing.JRadioButton();
        rbTrabajadorNombre = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        bBuscar.setText("Buscar");
        bBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarActionPerformed(evt);
            }
        });

        bSalir.setText("Salir");
        bSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar por centro"));

        jLabel5.setText("Nombre Centro:");

        jLabel6.setText("ID Centro:");

        tfNombreCentro.setEnabled(false);
        tfNombreCentro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfNombreCentroFocusLost(evt);
            }
        });
        tfNombreCentro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNombreCentroActionPerformed(evt);
            }
        });

        tfIdCentro.setEnabled(false);
        tfIdCentro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfIdCentroFocusGained(evt);
            }
        });

        buttonGroup2.add(rbCentroId);
        rbCentroId.setText("buscar por ID");
        rbCentroId.setEnabled(false);
        rbCentroId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCentroIdActionPerformed(evt);
            }
        });

        buttonGroup2.add(rbCentroNombre);
        rbCentroNombre.setText("buscar por Nombre");
        rbCentroNombre.setEnabled(false);
        rbCentroNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCentroNombreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tfIdCentro, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tfNombreCentro, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rbCentroId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbCentroNombre)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbCentroId)
                    .addComponent(rbCentroNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfIdCentro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNombreCentro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Himevico2.png"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Trabajadores.png"))); // NOI18N

        cbTrabajador.setSelected(true);
        cbTrabajador.setText("Buscar por trabajador");
        cbTrabajador.setEnabled(false);
        cbTrabajador.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cbTrabajadorStateChanged(evt);
            }
        });
        cbTrabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTrabajadorActionPerformed(evt);
            }
        });

        cbCentro.setSelected(true);
        cbCentro.setText("Buscar por centro");
        cbCentro.setEnabled(false);
        cbCentro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCentroActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar por trabajador"));

        tfNombre.setEnabled(false);
        tfNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfNombreFocusGained(evt);
            }
        });

        jLabel1.setText("Nombre:");

        jLabel4.setText("Dni:");

        tfDni.setEnabled(false);
        tfDni.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfDniFocusGained(evt);
            }
        });
        tfDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDniActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbTrabajadorDni);
        rbTrabajadorDni.setText("buscar por DNI");
        rbTrabajadorDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbTrabajadorDniActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbTrabajadorNombre);
        rbTrabajadorNombre.setText("buscar por Nombre");
        rbTrabajadorNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbTrabajadorNombreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfDni, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(rbTrabajadorDni)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbTrabajadorNombre)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbTrabajadorDni)
                    .addComponent(rbTrabajadorNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(13, 13, 13)
                                    .addComponent(cbTrabajador)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cbCentro)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(bBuscar)
                        .addGap(18, 18, 18)
                        .addComponent(bSalir)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTrabajador)
                    .addComponent(cbCentro))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bBuscar)
                    .addComponent(bSalir))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void funcionCheckBox(boolean tipoCheck){
        if(cbTrabajador.isSelected()&&cbCentro.isSelected()){
            rbTrabajadorDni.setEnabled(true);
            rbTrabajadorNombre.setEnabled(true);
            rbCentroNombre.setEnabled(true);
            rbCentroId.setEnabled(true);
        }
        if (cbTrabajador.isSelected()&&!cbCentro.isSelected()){
            rbTrabajadorDni.setEnabled(true);
            rbTrabajadorNombre.setEnabled(true);
            rbCentroNombre.setEnabled(false);
            rbCentroId.setEnabled(false);
        }
        if (!cbTrabajador.isSelected()&&cbCentro.isSelected()){
            rbTrabajadorDni.setEnabled(false);
            rbTrabajadorNombre.setEnabled(false);
            rbCentroNombre.setEnabled(true);
            rbCentroId.setEnabled(true);
        }
        if (!cbTrabajador.isSelected()&&!cbCentro.isSelected()&&tipoCheck==true){
            cbCentro.setSelected(true);
            rbTrabajadorDni.setEnabled(false);
            rbTrabajadorNombre.setEnabled(false);
            rbCentroNombre.setEnabled(true);
            rbCentroId.setEnabled(true);
        }
        if(!cbTrabajador.isSelected()&&!cbCentro.isSelected()&&tipoCheck==false){
            cbTrabajador.setSelected(true);
            rbTrabajadorDni.setEnabled(true);
            rbTrabajadorNombre.setEnabled(true);
            rbCentroNombre.setEnabled(false);
            rbCentroId.setEnabled(false);
        }
    }
    private void funcionRadioBoton(boolean tipoRb){
        cbTrabajador.setEnabled(false);
        cbCentro.setEnabled(false);
        if(rbTrabajadorDni.isSelected()&&tipoRb==true){
            tfDni.setEnabled(true);
            tfNombre.setEnabled(false);
        }
        if(rbTrabajadorNombre.isSelected()&&tipoRb==true){
            tfDni.setEnabled(false);
            tfNombre.setEnabled(true);
        }
        if(rbCentroNombre.isSelected()&&tipoRb==false){
            tfIdCentro.setEnabled(false);
            tfNombreCentro.setEnabled(true);
        }
        if(rbCentroId.isSelected()&&tipoRb==false){
            tfNombreCentro.setEnabled(false);
            tfIdCentro.setEnabled(true);
        }
    }
    /*
    private void funcionDisableRb(boolean tipoRb){
        if(tipoRb==true){
           rbTrabajadorNombre.setEnabled(false);
           rbTrabajadorDni.setEnabled(false); 
        }
        if(tipoRb==false){
           rbCentroNombre.setEnabled(false);
           rbCentroId.setEnabled(false); 
        }  
    }*/
    private void cbTrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTrabajadorActionPerformed
         funcionCheckBox(true);
    }//GEN-LAST:event_cbTrabajadorActionPerformed

    private void cbTrabajadorStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cbTrabajadorStateChanged
        
    }//GEN-LAST:event_cbTrabajadorStateChanged

    private void rbTrabajadorDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbTrabajadorDniActionPerformed
        funcionRadioBoton(true);
    }//GEN-LAST:event_rbTrabajadorDniActionPerformed

    private void rbTrabajadorNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbTrabajadorNombreActionPerformed
        funcionRadioBoton(true);
    }//GEN-LAST:event_rbTrabajadorNombreActionPerformed

    private void tfDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDniActionPerformed

    private void tfDniFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfDniFocusGained
       // funcionDisableRb(true);
    }//GEN-LAST:event_tfDniFocusGained

    private void tfNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfNombreFocusGained
       // funcionDisableRb(true);
    }//GEN-LAST:event_tfNombreFocusGained

    private void bSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirActionPerformed
        G2vJovi.cerrarVentanaBuscarTrabajador();
    }//GEN-LAST:event_bSalirActionPerformed

    private void bBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscarActionPerformed
        ArrayList <Trabajador> consulta = new ArrayList();
        String cadenaSalida="";
        if(rbTrabajadorNombre.isSelected()){
            consulta=main.ejecutarconsultaNombreC(tfNombre.getText().toUpperCase());
        }
        if (rbTrabajadorDni.isSelected()){
            consulta=main.ejecutarconsultasPk(tfDni.getText().toUpperCase());
        }
        if (!rbTrabajadorDni.isSelected()&&!rbTrabajadorNombre.isSelected()){
            consulta=main.ejecutarconsultasListaTrab();   
        }
        for(int x=0;x<consulta.size();x++){
            cadenaSalida+="DNI: "+consulta.get(x).getDni()+"\nNombre: "+consulta.get(x).getNombre()+"\nApellidos: "+consulta.get(x).getApellidoUno()+" "+consulta.get(x).getApellidoDos()+"\nDirección (Calle,Portal,Piso,Mano): "+consulta.get(x).getCalle()+", "+consulta.get(x).getPostal()+", "+consulta.get(x).getPiso()+", "+consulta.get(x).getMano()+"\nTelefono Personal: "+consulta.get(x).getTelefonoPersonal()+"\nTelefono Empresa: "+consulta.get(x).getTelefonoEmpresa()+"\nSalario: "+consulta.get(x).getSalario()+"\nFecha Nacimiento: "+consulta.get(x).getFechaNac()+"\nTipo: "+consulta.get(x).getClass().getSimpleName()+"\n---------------------------\n";
        }
       
        javax.swing.JOptionPane.showMessageDialog(null, cadenaSalida);
    }//GEN-LAST:event_bBuscarActionPerformed

    private void cbCentroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCentroActionPerformed
        funcionCheckBox(false);
    }//GEN-LAST:event_cbCentroActionPerformed

    private void rbCentroNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCentroNombreActionPerformed
        funcionRadioBoton(false);
    }//GEN-LAST:event_rbCentroNombreActionPerformed

    private void rbCentroIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCentroIdActionPerformed
        funcionRadioBoton(false);
    }//GEN-LAST:event_rbCentroIdActionPerformed

    private void tfIdCentroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfIdCentroFocusGained
       // funcionDisableRb(false);
    }//GEN-LAST:event_tfIdCentroFocusGained

    private void tfNombreCentroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNombreCentroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNombreCentroActionPerformed

    private void tfNombreCentroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfNombreCentroFocusLost
       // funcionDisableRb(false);
    }//GEN-LAST:event_tfNombreCentroFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BuscarTrabajador dialog = new BuscarTrabajador(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBuscar;
    private javax.swing.JButton bSalir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JCheckBox cbCentro;
    private javax.swing.JCheckBox cbTrabajador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton rbCentroId;
    private javax.swing.JRadioButton rbCentroNombre;
    private javax.swing.JRadioButton rbTrabajadorDni;
    private javax.swing.JRadioButton rbTrabajadorNombre;
    private javax.swing.JTextField tfDni;
    private javax.swing.JTextField tfIdCentro;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfNombreCentro;
    // End of variables declaration//GEN-END:variables
}
